definitions:
  album.Album:
    properties:
      artist:
        type: string
      id:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
  album.albumDTO:
    properties:
      artist:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
info:
  contact: {}
  description: Dummy API as first go project
  title: Music API
  version: "1.0"
paths:
  /albums:
    get:
      consumes:
      - application/json
      description: get all albums
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/album.Album'
            type: array
      summary: Get all albums
      tags:
      - Albums
    post:
      consumes:
      - application/json
      parameters:
      - description: DTO for Album creation
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/album.albumDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/album.Album'
      summary: Create a new Album
      tags:
      - Albums
  /albums/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID of Item
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: ""
      summary: Delete a album Album
      tags:
      - Albums
    put:
      consumes:
      - application/json
      parameters:
      - description: ID of Item
        in: path
        name: id
        required: true
        type: string
      - description: DTO for update the album
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/album.albumDTO'
      responses:
        "200":
          description: ""
      summary: Update a album
      tags:
      - Albums
swagger: "2.0"
